### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ottlinger/fotorenamer#10]
```
Add basic localization (take care of encoding issues for German umlauts).

Open topic:
how to introduce i18n to the html page?!
(should it be filtered during mvn run?)
```

Original issue reported on code.google.com by `fotorena...@aiki-it.de` on 23 Aug 2011 at 6:01

**Comment by ottlinger** [comment]
* [ ] Localize all contents
* [ ] Add documentation and example on how to change the UI language
* [ ] en and de

**Comment by ottlinger** [comment]
Only German - will provide English as soon as requested.
