### ISSUE TITLE
Enhancement: Provide a means to keep interaction between FileChooser and Textfield

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ottlinger/fotorenamer#12]
```
to allow a user to enter something in there which get's validated when clicking 
the button to open the file chooser.

The following scenario should be possible:
* enter /foo/something in textfield
* click on button
* directory chooser starts in /foo/something
* --or deletes the text field if the fiel/dir does not exist- not implemented to allow a user to change a typo--
```

Original issue reported on code.google.com by `fotorena...@aiki-it.de` on 23 Aug 2011 at 6:04

**Comment by ottlinger** [comment]
# Solution
Drag'n'drop works for multiple selections and takes the first available directory.
Furthermore any text input in the textfield is taken as a start directory for the filechooser, in case of exceptions you may change the text (cancel) or navigate to the correct location.

**Comment by ottlinger** [comment]
DONE.
